import pandas as pd
import ast
import os

# AI生成代码识别关键词
AI_CODE_KEYWORDS = {"copilot", "ai generated", "generated by ai", "chatgpt", 
                    "ai-assisted", "ai生成", "自动生成", "gpt", "llm generated"}

def has_ai_generated_code(title, body, commit_msgs):
    # 拼接所有文本并转小写
    all_text = f"{title} {body} {' '.join(commit_msgs)}".lower()
    return any(keyword in all_text for keyword in AI_CODE_KEYWORDS)

def safe_eval_list(s):
    """安全解析列表字符串"""
    try:
        return ast.literal_eval(s)
    except:
        return []

if __name__ == "__main__":
    # 读取三张表
    pr_basic = pd.read_csv("data/all_pr_basic.csv", encoding="utf-8-sig")
    pr_reviews = pd.read_csv("data/all_pr_reviews.csv", encoding="utf-8-sig")
    pr_code = pd.read_csv("data/all_code_changes.csv", encoding="utf-8-sig")
    
    # 1. 评审维度聚合统计
    if len(pr_reviews) > 0:
        review_agg = pr_reviews.groupby(["repo", "pr_id"]).agg(
            reviewer_count=("reviewer", "nunique"),
            comment_count=("review_comment", "count"),
            has_ai_reviewer=("is_ai_reviewer", "any")
        ).reset_index()
    else:
        review_agg = pd.DataFrame(columns=["repo", "pr_id", "reviewer_count", "comment_count", "has_ai_reviewer"])
    
    # 2. 合并三张表
    feature_df = pr_basic.merge(pr_code, on=["repo", "pr_id"], how="left")
    feature_df = feature_df.merge(review_agg, on=["repo", "pr_id"], how="left")
    
    # 3. 缺失值填充
    feature_df["reviewer_count"] = feature_df["reviewer_count"].fillna(0).astype(int)
    feature_df["comment_count"] = feature_df["comment_count"].fillna(0).astype(int)
    feature_df["has_ai_reviewer"] = feature_df["has_ai_reviewer"].fillna(False)
    feature_df["file_count"] = feature_df["file_count"].fillna(0).astype(int)
    
    # 4. 计算所有特征
    # PR长度 = 标题字符数 + 正文字符数
    feature_df["pr_length"] = feature_df.apply(
        lambda x: len(str(x["title"])) + len(str(x["body"])), axis=1
    )
    # Label数量
    feature_df["label_count"] = feature_df["labels"].apply(lambda x: len(safe_eval_list(x)))
    # 是否包含AI生成代码
    feature_df["commit_messages"] = feature_df["commit_messages"].apply(safe_eval_list)
    feature_df["has_ai_generated_code"] = feature_df.apply(
        lambda x: has_ai_generated_code(str(x["title"]), str(x["body"]), x["commit_messages"]), axis=1
    )
    
    # 5. 保存最终特征表
    feature_df.to_csv("data/pr_feature_table.csv", index=False, encoding="utf-8-sig")
    print("特征表构建完成！")
    print(f"总PR数：{len(feature_df)}")
    print(f"特征列：{list(feature_df.columns)}")
    print("已保存到 data/pr_feature_table.csv")